Feature/add branch version to header file
elbb/bb-gitversion pull request #26
Opened 2020-06-22 13:56 UTC by JoergZeidler

2020-06-23 07:09 UTC, siredmar requested changes

2020-06-23 07:09 UTC, siredmar commented on gitversion/entrypoint.sh
> +mv ${JSON_DIR}/gitversion_append.json ${JSON_DIR}/gitversion.json
the `rm` is not needed. the `mv` will overwrite the old file.

2020-06-23 07:09 UTC, siredmar commented on CHANGELOG.md
> +-   added branch name to gitversion json file
1. You are not adding the branch name, you are adding the `branch version`. See Readme for an explanation. Also you need to adapt the Readme that states the old `branch version` behavior. 
2. The change has a lot of more impact than just adding a value to the json file. The generated files (plain, env, and cpp) now also contain the `branch version`.

2020-06-23 07:09 UTC, siredmar commented on CHANGELOG.md
> +-   added branch name to gitversion json file
Another thing not related to this PR:
Please remove the space between char and asterisk in this line https://github.com/elbb/bb-gitversion/blob/58073c46832e065c08141b7f39877d8c8edd2859/gitversion/templates/cpp/version.h.j2#L7
what i expect:
`constexpr const char* sometext`

2020-06-24 06:29 UTC, JoergZeidler commented on gitversion/entrypoint.sh
> +mv ${JSON_DIR}/gitversion_append.json ${JSON_DIR}/gitversion.json
OK, will fix with next commit.

2020-06-24 06:51 UTC, siredmar approved these changes

2020-06-24 06:57 UTC, merged