Fix pipeline race
elbb/bb-gitversion pull request #38
Opened 2021-06-29 09:46 UTC by mlilien

2021-06-29 10:07 UTC, JanZachmann submitted a review, later dismissed
Fine for me but @JoergZeidler is supposed to be in a better postion for review.

2021-06-30 05:54 UTC, JoergZeidler requested changes

2021-06-30 05:54 UTC, JoergZeidler commented on README.md
> +After successfully uploading the pipeline to concourse CI login and unpause it. After that the pipeline should be triggered by new commits on the master branch (or new tags if enabled in `ci/pipeline
master -> main

2021-06-30 12:08 UTC, mlilien commented on README.md
> +After successfully uploading the pipeline to concourse CI login and unpause it. After that the pipeline should be triggered by new commits on the master branch (or new tags if enabled in `ci/pipeline
done

2021-06-30 12:10 UTC, JoergZeidler approved these changes

2021-06-30 14:05 UTC, merged